scanner:
    diff_only: False  # If False, the entire file touched by the Pull Request is scanned for errors. If True, only the diff is scanned.

pycodestyle:  # Same as scanner.linter value. Other option is flake8
    max-line-length: 100  # Default is 79 in PEP 8
    ignore:
        - E203  # Whitespace before :, not a strict PEP8 requirement and sometimes incompatible with black.
        - W503  # Deprecated, incompatible with black.

no_blank_comment: False  # If True, no comment is made on PR without any errors.

message:  # Customize the comment made by the bot
    opened:  # Messages when a new PR is submitted
                # The keyword {name} is converted into the author's username
        footer: "You can automatically repair most issues by commenting `@pep8speaks pep8ify` on GitHub or by locally running: `python -m autopep8 --max-line-length 100  --in-place --aggressive  --aggressive  ./*.py ./*/*.py ./*/*/*.py`"
                # The messages can be written as they would over GitHub
    updated:  # Messages when new commits are added to the PR
        footer: "You can automatically repair most issues by locally running: `python -m autopep8 --max-line-length 100  --in-place --aggressive  --aggressive  ./*.py ./*/*.py ./*/*/*.py`"
