

python main.py --config jiant/config/taskmaster/base_roberta.conf --overrides "exp_name = \"senteval\", run_name = se-probing-sentence-length, cuda=0, input_module=roberta-large, tokenizer=roberta-large, pretrain_tasks=se-probing-sentence-length, target_tasks=se-probing-sentence-length,  lr=0.001, do_pretrain = 1, do_target_task_training = 0, do_full_eval = 1"
python main.py --config jiant/config/taskmaster/base_roberta.conf --overrides "exp_name = \"senteval\", run_name = se-probing-bigram-shift, cuda=0, input_module=roberta-large, tokenizer=roberta-large, pretrain_tasks=se-probing-bigram-shift, target_tasks=se-probing-bigram-shift,  lr=0.001, do_pretrain = 1, do_target_task_training = 0, do_full_eval = 1"
python main.py --config jiant/config/taskmaster/base_roberta.conf --overrides "exp_name = \"senteval\", run_name = se-probing-past-present, cuda=0, input_module=roberta-large, tokenizer=roberta-large, pretrain_tasks=se-probing-past-present, target_tasks=se-probing-past-present,  lr=0.001, do_pretrain = 1, do_target_task_training = 0, do_full_eval = 1"
python main.py --config jiant/config/taskmaster/base_roberta.conf --overrides "exp_name = \"senteval\", run_name = se-probing-odd-man-out, cuda=0, input_module=roberta-large, tokenizer=roberta-large, pretrain_tasks=se-probing-odd-man-out, target_tasks=sse-probing-odd-man-out,  lr=0.001, do_pretrain = 1, do_target_task_training = 0, do_full_eval = 1"
python main.py --config jiant/config/taskmaster/base_roberta.conf --overrides "exp_name = \"senteval\", run_name = se-probing-coordination-inversion, cuda=0, input_module=roberta-large, tokenizer=roberta-large, pretrain_tasks=se-probing-coordination-inversion, target_tasks=se-probing-coordination-inversion,  lr=0.001, do_pretrain = 1, do_target_task_training = 0, do_full_eval = 1"
python main.py --config jiant/config/taskmaster/base_roberta.conf --overrides "exp_name = \"senteval\", run_name = se-probing-word-content, cuda=0, input_module=roberta-large, tokenizer=roberta-large, pretrain_tasks=se-probing-word-content, target_tasks=se-probing-word-content,  lr=0.001, do_pretrain = 1, do_target_task_training = 0, do_full_eval = 1"
python main.py --config jiant/config/taskmaster/base_roberta.conf --overrides "exp_name = \"senteval\", run_name = se-probing-tree-depth, cuda=0, input_module=roberta-large, tokenizer=roberta-large, pretrain_tasks=se-probing-tree-depth, target_tasks=se-probing-tree-depth,  lr=0.001, do_pretrain = 1, do_target_task_training = 0, do_full_eval = 1"
python main.py --config jiant/config/taskmaster/base_roberta.conf --overrides "exp_name = \"senteval\", run_name = se-probing-top-constituents, cuda=0, input_module=roberta-large, tokenizer=roberta-large, pretrain_tasks=se-probing-top-constituents, target_tasks=se-probing-top-constituents,  lr=0.001, do_pretrain = 1, do_target_task_training = 0, do_full_eval = 1"
python main.py --config jiant/config/taskmaster/base_roberta.conf --overrides "exp_name = \"senteval\", run_name = se-probing-subj-number, cuda=0, input_module=roberta-large, tokenizer=roberta-large, pretrain_tasks=se-probing-subj-number, target_tasks=se-probing-subj-number, lr=0.001, do_pretrain = 1, do_target_task_training = 0, do_full_eval = 1"
python main.py --config jiant/config/taskmaster/base_roberta.conf --overrides "exp_name = \"senteval\", run_name = se-probing-obj-number, cuda=0, input_module=roberta-large, tokenizer=roberta-large, pretrain_tasks=se-probing-obj-number, target_tasks=se-probing-obj-number, lr=0.001, do_pretrain = 1, do_target_task_training = 0, do_full_eval = 1"
