PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="sst 1 10 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="sst 1 10 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="socialiqa 2 10 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="socialiqa 2 10 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="ccg 2 10 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="ccg 2 10 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="qqp 2 5 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="qqp 2 5 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="qqp 2 5 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="qqp 2 5 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="mnli 2 5 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="mnli 2 5 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="mnli 2 5 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="mnli 2 5 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="scitail 1 10 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="scitail 1 10 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="qasrl 2 5 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="qasrl 2 5 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="qasrl 2 5 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="qasrl 2 5 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="qamr 1 10 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="qamr 1 10 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="cosmosqa 4 10 albert-xxlarge-v2" sbatch ~/4p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="cosmosqa 4 10 albert-xxlarge-v2" sbatch ~/4p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="hellaswag 4 10 albert-xxlarge-v2" sbatch ~/4p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="hellaswag 4 10 albert-xxlarge-v2" sbatch ~/4p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="commonsenseqa 2 20 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="record 4 5 albert-xxlarge-v2" sbatch ~/4p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="record 4 5 albert-xxlarge-v2" sbatch ~/4p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="record 4 5 albert-xxlarge-v2" sbatch ~/4p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="record 4 5 albert-xxlarge-v2" sbatch ~/4p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="winogrande 1 10 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="winogrande 1 10 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="sst-20k 1 10 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="sst-20k 1 10 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="socialiqa-20k 2 10 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="socialiqa-20k 2 10 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="ccg-20k 2 10 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="ccg-20k 2 10 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="qqp-20k 2 10 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="qqp-20k 2 10 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="mnli-20k 2 10 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="mnli-20k 2 10 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="scitail-20k 1 10 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="scitail-20k 1 10 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="qasrl-20k 2 10 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="qasrl-20k 2 10 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="qamr-20k 1 10 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="qamr-20k 1 10 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="cosmosqa-20k 4 10 albert-xxlarge-v2" sbatch ~/4p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="cosmosqa-20k 4 10 albert-xxlarge-v2" sbatch ~/4p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="hellaswag-20k 4 10 albert-xxlarge-v2" sbatch ~/4p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="hellaswag-20k 4 10 albert-xxlarge-v2" sbatch ~/4p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="record-20k 4 10 albert-xxlarge-v2" sbatch ~/4p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="record-20k 4 10 albert-xxlarge-v2" sbatch ~/4p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="winogrande-20k 1 10 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="winogrande-20k 1 10 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="rte 2 20 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="boolq 2 20 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="commitbank 2 20 albert-xxlarge-v2" sbatch ~/2p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="copa 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="multirc 4 10 albert-xxlarge-v2" sbatch ~/4p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="multirc 4 10 albert-xxlarge-v2" sbatch ~/4p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="wic 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="winograd-coreference 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="edges-ner-ontonotes 1 10 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="edges-ner-ontonotes 1 10 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="edges-srl-ontonotes 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="edges-srl-ontonotes 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="edges-srl-ontonotes 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="edges-srl-ontonotes 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="edges-coref-ontonotes 1 10 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="edges-coref-ontonotes 1 10 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="edges-spr1 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="edges-spr2 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="edges-dpr 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="edges-rel-semeval 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="edges-pos-ontonotes 1 10 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="edges-pos-ontonotes 1 10 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="edges-nonterminal-ontonotes 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="edges-nonterminal-ontonotes 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="edges-nonterminal-ontonotes 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="edges-nonterminal-ontonotes 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="edges-dep-ud-ewt 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-word-content 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-word-content 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-word-content 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-word-content 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-tree-depth 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-tree-depth 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-tree-depth 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-tree-depth 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-top-constituents 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-top-constituents 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-top-constituents 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-top-constituents 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-bigram-shift 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-bigram-shift 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-bigram-shift 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-bigram-shift 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-past-present 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-past-present 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-past-present 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-past-present 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-subj-number 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-subj-number 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-subj-number 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-subj-number 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-obj-number 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-obj-number 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-obj-number 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-obj-number 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-odd-man-out 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-odd-man-out 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-odd-man-out 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-odd-man-out 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-coordination-inversion 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-coordination-inversion 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-coordination-inversion 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-coordination-inversion 1 5 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-sentence-length 1 10 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-sentence-length 1 10 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="acceptability-wh 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="acceptability-def 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="acceptability-conj 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="acceptability-eos 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="cola 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="edges-ner-ontonotes-5k 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="edges-srl-ontonotes-5k 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="edges-coref-ontonotes-5k 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="edges-pos-ontonotes-5k 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="edges-nonterminal-ontonotes-5k 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="edges-dep-ud-ewt-5k 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-word-content-5k 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-tree-depth-5k 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-top-constituents-5k 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-bigram-shift-5k 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-past-present-5k 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-subj-number-5k 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-obj-number-5k 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-odd-man-out-5k 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-coordination-inversion-5k 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="se-probing-sentence-length-5k 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
PROG="scripts/taskmaster/optuna_hp_search/run_trials" ARGS="cola-5k 1 20 albert-xxlarge-v2" sbatch ~/p40.sbatch
